<?php

  $databaseHost="localhost"; 
  $PHPDomainHost="localhost"; 
	
    // define the sys admin email
  $admin_email = "brent@heigoldinvestments.com";

    // define the default database server
  $defaultRDBMS = "MYSQL";

    // define the default RDBMS host address
  $defaultHost = "$databaseHost";

    // define the default username
  $defaultUsername = "root";

    // define the default password
  $defaultPassword = "heimer27";

    // define the default database
  $defaultDB = "devTrak";
  
///////////////////////////////////////////////////////////////////////////////////
//
// Global Variables
//
///////////////////////////////////////////////////////////////////////////////////

	// Coworker data
	$position = array("Account Executive","Management","Processor","Programmer","Project Manager");
	$facility = array("Oxnard","Dallas");

?>
